        !COMPILER-GENERATED INTERFACE MODULE: Mon Apr 02 14:17:38 2018
        MODULE INPUT_CAAOUTPUTCONTROL__genmod
          INTERFACE 
            SUBROUTINE INPUT_CAAOUTPUTCONTROL
            END SUBROUTINE INPUT_CAAOUTPUTCONTROL
          END INTERFACE 
        END MODULE INPUT_CAAOUTPUTCONTROL__genmod
