        !COMPILER-GENERATED INTERFACE MODULE: Sun Apr 01 23:34:10 2018
        MODULE OUTPUT_CAATECPLOT__genmod
          INTERFACE 
            SUBROUTINE OUTPUT_CAATECPLOT(TEC_OUTPUTTIMES,TIMENOW)
              INTEGER(KIND=4) :: TEC_OUTPUTTIMES
              REAL(KIND=4) :: TIMENOW
            END SUBROUTINE OUTPUT_CAATECPLOT
          END INTERFACE 
        END MODULE OUTPUT_CAATECPLOT__genmod
